### PR TITLE
Fixed a bug with  0 autocloseTimeout

### PR DESCRIPTION
**Pull request by marsaud**

### CODE REVIEW

**Comment by marsaud** [comment]
This may fix #6 and probably #3

**Comment by bvankeir** [comment]
Hi @marsaud, I think your suggestion is a good one, to fall back to 0 for autoCloseTimeout as this is the expected behaviour. However, if this fix would be pulled into the base branch, this behaviour should also be reflected in the readme where it actually is explicitly listed that the autoCloseTimeout option defaults to 10 seconds.

**Comment by marsaud** [comment]
I don't understand, once the bug is fixed, the behaviour WILL be the one reflected in the readme...so what ?

**Comment by bvankeir** [comment]
Well, as far as I understood, in issue #6 the problem was that people assume that the connection does not time out (i.e. fs-like behaviour), but there is an autoCloseTimeout parameter that defaults to 10 seconds. By setting autoCloseTimeout to 0 as an option to the constructor, the issue was resolved (strangely enough, as your bug fix shows that this should not have any effect. I probably didn't test well enough).

I didn't deeply investigate your bugfix, but I assumed that you made the option default to 0 as well. Now looking at your code, I see that you fixed an important bug indeed.

Still, I would advocate for making the autoCloseTimeout default to 0, which would need a small change in the code and in the readme.

**Comment by marsaud** [comment]
No, in fact the issues were not solved by the 0 autoCloseTimeout, that was the bug.

What some people may not expect, is that the timeout "cuts" the stuff while in use...In my opinion, a client timeout should be evaluated from the last use, or responseless request attempt, not from start or opening.

Wether the default timeout should be zero or not, I don't really care. As soon as all is well documented, and works as documented, it will be ok for me :)

**Comment by arivera12** [comment]
@marsaud  
@bchelli 
autoCloseTimeout: 0 doesn't fix this issue. I trying to read and write a file that is 8.50 GB and its only transfers 945,791 KB from 9,334,399 KB. I have enough space to read/write that file size correctly. It doesn't launch any error. Don't know what is going on :(. Any help?

**Pull request merged**
